name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # ganti sesuai versi Go kamu

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install swag cli (untuk generate swagger.json)
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      # 5. Generate swagger docs
      - name: Generate Swagger docs
        run: swag init -g main.go -o docs

      # 6. Verify formatting
      - name: Go fmt
        run: go fmt ./...

      # 7. Run tests
      - name: Run tests
        run: go test ./... -v

      # 8. Build binary
      - name: Build
        run: go build -o app .